### ISSUE TITLE
flutter_tags is incompatible with Dart3 and newest flutter version

### ISSUE THREAD

**Issue by ning-quantvortex** [TencentCloud/chat-demo-flutter#8]
Error when flutter run
```
Because flutter_tags 0.4.9+1 doesn't support null safety and no versions of flutter_tags match >0.4.9+1 <0.5.0,
  flutter_tags ^0.4.9+1 is forbidden.
So, because tencent_cloud_chat_demo depends on flutter_tags ^0.4.9+1, version solving failed.

The lower bound of "sdk: '>=2.0.0 <3.0.0'" must be 2.12.0 or higher to enable null safety
```

Reference: https://pub.dev/packages/flutter_tags/versions

Current I can downgrade flutter version. But you guys have to fix it, because flutter_tags doesn't update for two years and is incompatible with Dart3

**Comment by harshhhh15** [comment]
You appear to be experiencing two issues while attempting to execute your Flutter application. To begin, flutter_tags version 0.4.9+1 does not support null safety, and no version matching the range >0.4.9+1 0.5.0 is available. The version solver is failing as a result of this.


One approach could be to upgrade flutter_tags to a version that supports null safety. You can upgrade to a later version, preferably 0.5.0 or higher, which should offer null safety. This may be accomplished by upgrading your pubspec.yaml file to use a newer version of flutter_tags and running flutter pub. Download the updated package.
The second issue is that your SDK version must be at least 2.12.0 in order to enable null safety. Run flutter --version in your terminal to determine your current SDK version. If your SDK version is less than 2.12.0, you can update it in your terminal by typing flutter upgrade.

You should be able to execute your Flutter application without any problems after updating both the SDK version and the flutter_tags package. If you continue to have problems, try executing flutter clean to clear any cached dependencies and rebuild your application.

**Comment by RoleWong** [comment]
Hi, we fixed this issue in the latest version, while removing the dependency of flutter_tags.

**Comment by RoleWong** [comment]
Hi, we have addressed this issue in the latest version by removing the dependency on `flutter_tags`. Please pull the latest code and give it another try. Thank you!

**Comment by AlvinZhang0325** [comment]
ecause flutter_baidu_mapapi_map >=3.3.0 depends on device_info_plus ^4.0.3 and tencent_cloud_chat_uikit >=2.1.0 <2.1.0+1 depends on device_info_plus ^9.0.1, flutter_baidu_mapapi_map >=3.3.0 is incompatible with tencent_cloud_chat_uikit >=2.1.0 <2.1.0+1.
And because tencent_cloud_chat_uikit >=2.1.0+1 depends on flutter_svg ^2.0.6, if flutter_baidu_mapapi_map >=3.3.0 and tencent_cloud_chat_uikit >=2.1.0 then flutter_svg ^2.0.6.
And because tencent_cloud_chat_uikit <2.1.0 depends on intl ^0.17.0 and every version of flutter_localizations from sdk depends on intl 0.18.0, if flutter_baidu_mapapi_map >=3.3.0 and tencent_cloud_chat_uikit any and flutter_localizations from sdk then flutter_svg ^2.0.6.
And because tencent_cloud_chat_demo depends on both flutter_localizations from sdk and tencent_cloud_chat_uikit ^2.0.0, flutter_baidu_mapapi_map >=3.3.0 requires flutter_svg ^2.0.6.
So, because tencent_cloud_chat_demo depends on both flutter_baidu_mapapi_map ^3.3.1 and flutter_svg ^1.0.3, version solving failed.


I got this issue when I remove flutter_tags from dependencies ?

**Comment by RoleWong** [comment]
> ecause flutter_baidu_mapapi_map >=3.3.0 depends on device_info_plus ^4.0.3 and tencent_cloud_chat_uikit >=2.1.0 <2.1.0+1 depends on device_info_plus ^9.0.1, flutter_baidu_mapapi_map >=3.3.0 is incompatible with tencent_cloud_chat_uikit >=2.1.0 <2.1.0+1. And because tencent_cloud_chat_uikit >=2.1.0+1 depends on flutter_svg ^2.0.6, if flutter_baidu_mapapi_map >=3.3.0 and tencent_cloud_chat_uikit >=2.1.0 then flutter_svg ^2.0.6. And because tencent_cloud_chat_uikit <2.1.0 depends on intl ^0.17.0 and every version of flutter_localizations from sdk depends on intl 0.18.0, if flutter_baidu_mapapi_map >=3.3.0 and tencent_cloud_chat_uikit any and flutter_localizations from sdk then flutter_svg ^2.0.6. And because tencent_cloud_chat_demo depends on both flutter_localizations from sdk and tencent_cloud_chat_uikit ^2.0.0, flutter_baidu_mapapi_map >=3.3.0 requires flutter_svg ^2.0.6. So, because tencent_cloud_chat_demo depends on both flutter_baidu_mapapi_map ^3.3.1 and flutter_svg ^1.0.3, version solving failed.
> 
> I got this issue when I remove flutter_tags from dependencies ?

Plz pull the latest verion of the sample app from this repo. In the latest version, we not only remove flutter_tags, but all packages from Baidu map. Additionally, we make sure this sample app can run on Flutter 3.10 and Dart 3.0. You can have a try, and do not hesitate to contact us if still other problems occured.

**Comment by hexingcheng** [comment]
Hi, we have addressed this issue in the latest version by removing the dependency on flutter_tags. And our latest version has been migrated to Flutter 3.10 and Dart 3. Please pull the latest code and give it another try. Thank you!
